### ISSUE TITLE
Unable to exclude files from indexing based on directories

### ISSUE THREAD

**Issue by robbiejaeger** [algolia/algoliasearch-jekyll#52]
I would like to exclude files from being indexed in my Jekyll site based on the directory the files are in. There are too many files in some directories to exclude them one-by-one. I have tried specifying this in my `_config.yml` file, but it does not seem to work:

```yaml
algolia:
  excluded_files:
    - index.html
    - calendars/index.html
    - !ruby/regexp "/archive./"
```

`archive` is a directory at the root of my Jekyll project, and it contains many files. It would be great to exclude all of the files in `archive` using some kind of wildcard or regex.

**Comment by robbiejaeger** [comment]
I was overcomplicating things. I just needed:

```yaml
algolia:
  excluded_files:
    - index.html
    - calendars/index.html
    - archive
```
