### ISSUE TITLE
Synonyms deleted on index

### ISSUE THREAD

**Issue by mkiser** [algolia/algoliasearch-jekyll#62]
I set synonyms in the Algolia dashboard and save. I can query and get the correct results. 

When I `bundle exec jekyll algolia push` to reindex posts, the synonyms get erased. 

Here's a snippet of my `_config.yml` file:

```
algolia:
  application_id: ID
  index_name: INDEX
  read_only_api_key: KEY
  record_css_selector: p,li,blockquote
  excluded_files:
  ...
  settings:
    attributesToIndex:
    - unordered(text)
    - posted_at
    - title
    - h1
    distinct: false
```

Any help or possible work arounds here? 

x-posted to the [Algolia community board](https://discourse.algolia.com/t/synonyms-getting-replaced-on-index/388/1).
